package com.sayhello.circus.data

import android.content.Context
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json

private val Context.worldStore by preferencesDataStore("world_events")

/**
 * In-app "what the cast is doing right now" feed. Every entry is generated by
 * the AI layer with no host-system effect. Capped to keep storage bounded.
 */
class WorldEventStore(private val context: Context) {

    @Serializable
    data class Event(
        val ts: Long,
        val characterId: String,
        val verb: String,
        val text: String,
    )

    private object Keys { val Log = stringPreferencesKey("events_json") }
    private val json = Json { ignoreUnknownKeys = true }
    private val serializer = ListSerializer(Event.serializer())
    private val maxEntries = 200

    suspend fun events(): List<Event> {
        val raw = context.worldStore.data.first()[Keys.Log] ?: return emptyList()
        return runCatching { json.decodeFromString(serializer, raw) }.getOrDefault(emptyList())
    }

    fun stream(): kotlinx.coroutines.flow.Flow<List<Event>> = context.worldStore.data.map { prefs ->
        val raw = prefs[Keys.Log] ?: return@map emptyList<Event>()
        runCatching { json.decodeFromString(serializer, raw) }.getOrDefault(emptyList())
    }

    suspend fun append(event: Event) {
        val current = (events() + event).takeLast(maxEntries)
        context.worldStore.edit {
            it[Keys.Log] = json.encodeToString(serializer, current)
        }
    }
}
